version: "3"
services:
    suporte-quarkus-backend:
        container_name: fluxo-caixa-backend
        image: fluxo-caixa-backend:latest
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.jvm
            args:
                - JAR_FILE=target/fluxo-caixa-backend-1.0.0.jar
                - CONTEXT=fluxo-caixa-backend
        ports:
            - 8081:8080
        environment:
            - SERVER_BANCO_USUARIO=postgres
            - SERVER_BANCO_SENHA=895674
            - SERVER_BANCO_IP_PORT=192.168.1.254:5432
            - SERVER_BANCO_BASE_NAME=fluxo-caixa