version: "3"
services:
    suporte-quarkus-backend:
        container_name: fluxo-caixa-backend
        image: fluxo-caixa-backend:latest
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.jvm
            args:
                - JAR_FILE=target/fluxo-caixa-backend-1.0.0.jar
                - CONTEXT=fluxo-caixa-backend
        ports:
            - 8001:8080
        env_file:
            - .env
        restart: always